### ISSUE TITLE
Seems to not filter on flake8-simplify class errors

### ISSUE THREAD

**Issue by eivindjahren** [TrueBrain/actions-flake8#45]
When using
```
      - name: flake8 Lint
        uses: TrueBrain/actions-flake8@v2
        with:
          plugins: flake8-simplify
          error_classes: 'E,F'
          warning_classes:'SIM'
```
I would expect SIM errors to become a warning, but it becomes a failing error
