### ISSUE TITLE
cannot add multiple per-file-ignores to extra arguments

### ISSUE THREAD

**Issue by JessicaS11** [TrueBrain/actions-flake8#50]
Hello! Thanks for the great action.

I'm trying to add a list of items to the flake8 `--per-file-ignores` argument. I've tried just about everything I can think of to supply it via the `extra arguments` line. The relevant part of my .yml:
```
- name: Annotate PR after running flake8
   uses: TrueBrain/actions-flake8@v2
   with:
     max_line_length: 88
     extra_arguments:
       --per-file-ignores=__init__.py:F401 test_granules.py:E501
```
results in a file-not-found error for test_granules.py. I've tried every combination of spaces, newlines, quotes, etc.  I can think of and cannot figure out how to properly pass multiple `--per-file-ignores` to flake8 via this action. For reference, passing `--per-file-ignores='__init__.py:F401 test_granules.py:E501'` to flake8 locally has the expected/desired behavior.

Any suggestions for how to make this work? Thanks!
